default:
  image: $CI_REGISTRY/ssz-da/shiny_container:0.0.0.9000
 
variables:
  CONTAINER_REGISTRY: $CI_REGISTRY
  CONTAINER_REGISTRY_USERNAME: $CI_REGISTRY_USER
  CONTAINER_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  CONTAINER_REPOSITORY: $SWID
  CONTAINER_IMAGE_NAME: $CI_PROJECT_NAME # used for container image name
  COMPONENT_NAME: $CI_PROJECT_NAME # used for component name (alias name) in umbrella chart
  GIT_STRATEGY: fetch
  APP_NAME: $TEST_NAME
 
stages:          # List of stages for jobs, and their order of execution
  - deploy
 
deploy-job:
  stage: deploy
  script:
    - Rscript -e "source('deploy.R')"
