default:
  image: $CI_REGISTRY/ssz-da/shiny_container:0.0.0.9005
 
variables:
  CONTAINER_REGISTRY: $CI_REGISTRY
  CONTAINER_REGISTRY_USERNAME: $CI_REGISTRY_USER
  CONTAINER_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  CONTAINER_REPOSITORY: $SWID
  CONTAINER_IMAGE_NAME: $CI_PROJECT_NAME # used for container image name
  COMPONENT_NAME: $CI_PROJECT_NAME # used for component name (alias name) in umbrella chart
  GIT_STRATEGY: fetch
 
stages:          # List of stages for jobs, and their order of execution
  - deploy_test
  - deploy_prod
 
deploy-job-test:
  # ausgeführt wenn push in merge request
  stage: deploy_test
  variables:
    APP_NAME: $TEST_NAME
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - Rscript -e "renv::deactivate()"
    - Rscript -e "packageVersion('rsconnect')"
    - Rscript -e "source('deploy.R')"

deploy-job-prod:
  # ausgeführt wenn Push auf Main branch
  stage: deploy_prod
  variables:
    APP_NAME: $PROD_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - Rscript -e "renv::deactivate()"
    - Rscript -e "packageVersion('rsconnect')"
    - Rscript -e "source('deploy.R')"