default:
  image: $CI_REGISTRY/docker-hub-proxy/rocker/tidyverse:4.2.1
 
variables:
  CONTAINER_REGISTRY: $CI_REGISTRY
  CONTAINER_REGISTRY_USERNAME: $CI_REGISTRY_USER
  CONTAINER_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  CONTAINER_REPOSITORY: $SWID
  CONTAINER_IMAGE_NAME: $CI_PROJECT_NAME # used for container image name
  COMPONENT_NAME: $CI_PROJECT_NAME # used for component name (alias name) in umbrella chart
  GIT_STRATEGY: fetch
  APP_NAME: $TEST_NAME
 
stages:          # List of stages for jobs, and their order of execution
  - build
 
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - install2.r rsconnect shiny reactable lubridate jpeg httr data.table Rcpp openxlsx readxl remotes
    - Rscript -e "remotes::install_github('StatistikStadtZuerich/zuericssstyle')"
    - Rscript -e "remotes::install_github('StatistikStadtZuerich/zuericolors')"
    - Rscript -e "remotes::install_github('mitchelloharawild/icons')"
    - Rscript deploy.R
