default:
  image: $CI_REGISTRY/docker-hub-proxy/ubuntu
 
variables:
  CONTAINER_REGISTRY: $CI_REGISTRY
  CONTAINER_REGISTRY_USERNAME: $CI_REGISTRY_USER
  CONTAINER_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  CONTAINER_REPOSITORY: $SWID
  CONTAINER_IMAGE_NAME: $CI_PROJECT_NAME # used for container image name
  COMPONENT_NAME: $CI_PROJECT_NAME # used for component name (alias name) in umbrella chart
  GIT_STRATEGY: fetch
 
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
 
build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - docker build -t main . 
    
deploy-job:       # This job runs in the build stage, which runs first.
  stage: deploy
  script:
    - docker run 
          -e SHINY_ACC_NAME=$SHINY_ACC_NAME
          -e TOKEN=$TOKEN 
          -e SECRET=$SECRET 
          -e APP_NAME=$TEST_NAME
          main