name: Run on pull request

# Run on all pull requests
on:
  pull_request: {}
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
      #- uses: r-lib/actions/setup-renv@v2
      #  with:
      #    profile: '"shiny"'

      # build the docker image and give it the name main
      - name: Build image
        env:
          SHINY_ACC_NAME: ${{ secrets.SHINY_ACC_NAME }}
          TOKEN: ${{ secrets.TOKEN }}
          SECRET: ${{ secrets.SECRET }}
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
          Rscript -e "Sys.getenv()"
          Rscript -e "install.packages('rsconnect')"
          Rscript -e "rsconnect::setAccountInfo(name = Sys.getenv('SHINY_ACC_NAME'), token = Sys.getenv('secrets.TOKEN'), secret = Sys.getenv('secrets.SECRET'))"
          #Rscript -e "renv::restore()"
          #Rscript -e "rsconnect::setAccountInfo(name = Sys.getenv('SHINY_ACC_NAME'), token = Sys.getenv('TOKEN'), secret = Sys.getenv('SECRET'))"
          #Rscript -e "rsconnect::deployApp(forceUpdate = TRUE, appName = Sys.getenv('TEST_NAME'))"
  
